### ISSUE TITLE
Scuts not haxelib (git) friendly - yet

### ISSUE THREAD

**Issue by sledorze** [frabbit/scuts#1]
Trying to use scuts from haxelib (not cloning by hand)
using:
haxelib git scuts https://github.com/frabbit/scuts.git

but problem is that there's several projects in there;
like scutsCore, scutsDs, etc.. each of those having their own source paths.

so to use any of those, one would need to refer to a subpath of the lib (not possible AFAIK).
I think we should split those; what do you think?

**Comment by frabbit** [comment]
before splitting i'm thinking about moving reactive to the core and have some kind of async package (moving promises there too), what do you think.

**Comment by frabbit** [comment]
or rename reactive to async and move promise there.

**Comment by frabbit** [comment]
Ok, i added the required haxelib.json files and some info to get it working on the main page. Tell me if it works for you?

**Comment by sledorze** [comment]
Weird,
I've installed everything as the main page states.

then use:
-lib scuts-ht
-main Main
-js out.js

with Main:
package ;

import scuts.ht.core.Ht;
...

and it errors with:
Class not found : scuts.ht.core.Ht

Weird as everything looks ok with the approach.. (maybe something on my
side)

On Sun, Jun 30, 2013 at 7:57 PM, frabbit notifications@github.com wrote:

> Ok, i added the required haxelib.json files and some info to get it
> working on the main page. Tell me if it works for you?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/frabbit/scuts/issues/1#issuecomment-20252224
> .

## 

Stéphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorzehttps://twitter.com/#!/stephaneledorze/status/74020060125077504

Tel: +33 (0) 6 08  76 70 15

**Comment by frabbit** [comment]
i just changed 

haxelib git scuts-mcore https://github.com/frabbit/scuts.git master scutsMcore

to

haxelib git scuts-mcore https://github.com/frabbit/scuts.git master scutsMCore

maybe that was the problem.

**Comment by frabbit** [comment]
no that wasn't the problem, i will look into it.
